# Generated by Django 4.1.4 on 2022-12-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_session_options_alter_session_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='items',
            field=models.ManyToManyField(to='main_app.item'),
        ),
    ]
